### ISSUE TITLE
Encourage Sponsorship via Open Collective

### ISSUE THREAD

**Issue by zspencer** [zinc-collective/www.momentpark.com#12]
In order to increase the time, attention, and energy available to contribute to MomentPark
As a Client
I would like to be able to sponsor the projects monthly.

See: https://opencollective.com/moment-park

### This issue may be closed when

1. [ ] The www.momentpark.com website has a link to the OpenCollective with a reasonable call-to-action 
2. [ ] We have updated our newsletter template to include a "Moment Park is supported by Artists Like You" that links to the sponsorship button
3. [ ] We have updated the newsletter template to include a section to thank the sponsors who were active between this newsletter and the previous one.

**Comment by zspencer** [comment]
I've spent a bit of time tweaking the [Moment Park open-collective](https://opencollective.com/moment-park)

In particular I:

1. Established a monthly and annual "dues" tier so that people can opt-in to making recurring contributions to the development of Moment Park.
2. I set a $75,000 per year goal; as that is the [living wage](https://livingwage.mit.edu/metros/41860) for a single person supporting a family of 5 in the highest-cost-of-living metro area in the U.S.
3. Added a brief description of the project, and linked to the [github project](https://github.com/orgs/zinc-collective/projects/3) and [website](https://www.momentpark.com/)

This isn't _perfect_ by any means, but it will hopefully serve as a seedling for capturing some of the enthusiasm for Moment Park.
